### ISSUE TITLE
New typing implementation doesn't work on API 28

### ISSUE THREAD

**Issue by eugene-krivobokov** [avito-tech/android-ui-testing#59]
EditTextTest

```
at com.avito.android.ui.test.EditTextTest.writesCyrillicText(EditTextTest.kt:33)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:527)
    ...
     Caused by: java.util.concurrent.ExecutionException: java.lang.NoSuchFieldException: No field mIInputContext in class Landroid/view/inputmethod/InputMethodManager; (declaration of 'android.view.inputmethod.InputMethodManager' appears in /system/framework/framework.jar!classes2.dex)


```

**Comment by dimorinny** [comment]
https://issuetracker.google.com/issues/140154283
